service: skill-sample-go-fact
frameworkVersion: ">=1.28.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  skill:
    handler: bin/facts
    events:
      - alexaSkill: ${file(env.yml):${self:custom.stage}.ALEXA_SKILL_ID}

